### ISSUE TITLE
where is the "position_encoding" function being called?

### ISSUE THREAD

**Issue by YilinLiu97** [NimrodShabtay/positional-encoding-image-prior#2]
Hi @EliSchwartz, the work is insightful! I'm just wondering where is the function "position_encoding" being used? I can see that the "generate_fourier_feature_maps" are called to generate the input. Thanks!

**Comment by NimrodShabtay** [comment]
Hi,
Thank you for your comment.
The function `positional_encoding` is indeed not being used anywhere.
It was used to test different frequency initiation schemes, but in the end, we chose the initiation scheme described in the paper so it's not being used.
I will remove it for clarity.
