### ISSUE TITLE
The multi-scale MLP in your paper can denoise

### ISSUE THREAD

**Issue by YilinLiu97** [NimrodShabtay/positional-encoding-image-prior#4]
Hi @NimrodShabtay, I've experimented with both your code and my own, and found that if you simply remove the noise perturbation happened at each iteration, the multi-scale MLP can denoise pretty well.

**Comment by NimrodShabtay** [comment]
Hi @YilinLiu97, Thanks for the comment.
Indeed PIP is not sensitive to noise perturbation noise like DIP.
Not only in Denoising but also in other tasks, such as SR and inpainting.

**Comment by YilinLiu97** [comment]
The multi-scale MLP can denoise even with the uniform noise as the input, i.e., under the DIP setting, as long as the `reg_noise_std` is set to 0.

**Comment by NimrodShabtay** [comment]
@YilinLiu97 Thanks for pointing this out.
It's indeed true for denoising, however I tried it on few examples in SR and removing the perturbation noise doesn't work fairly as good as in denoising (both for 3x3 kernels and 1x1 kernels)

**Comment by YilinLiu97** [comment]
@NimrodShabtay We found that the key to denoising with a multi-scale MLP is the unlearnt upsampling layer (https://arxiv.org/abs/2304.11409), e.g., bilinear upsampling. However, a plain MLP (i.e., w/o. upsampling) is indeed not able to denoise. 

And I agree that things are a bit tricker in super resolution. Maybe something yet to be understood about DIP w.r.t different tasks.

**Comment by YilinLiu97** [comment]
And I agree that things are a bit tricker in super resolution. Maybe something yet to be understood about DIP w.r.t different tasks.
